//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallRecording.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> EventTypeId { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Extension { get; set; }
        public Nullable<int> NumberTypeId { get; set; }
        public string Number { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> CallTypeId { get; set; }
        public Nullable<int> Status { get; set; }
        public string Message { get; set; }
    
        public virtual CallType CallType { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual NumberType NumberType { get; set; }
        public virtual Role Role { get; set; }
    }
}
